- src/lib.rs
> update to recent rust changes

- env/src/lib.rs
> Document where env-logger logs

- src/lib.rs
> Move __static_max_level to other hidden functions and add warning

- env/src/lib.rs
env_logger: Add config to Logger to allow changing the environmental variable, the default log level and the log format
```rust
#[macro_use]
extern crate log;
extern crate env_logger;
extern crate time;
use log::{LogRecord, LogLevelFilter};
use env_logger::LogConfig;
fn main() {
let formatter = |record: &LogRecord| {
let t = time::now();
format!("{},{:03} - {} - {}",
time::strftime("%Y-%m-%d %H:%M:%S", &t).unwrap(),
t.tm_nsec / 1000_000,
record.level(),
record.args()
)
};
let config = LogConfig {
env_var: "RUST_LOGGER",
format: Box::new(formatter),
level: LogLevelFilter::Info,
};
env_logger::init_with_config(config).unwrap();
error!("error message");
info!("info message");
}
```
> env_logger: Add config to Logger to allow changing log format etc

- src/lib.rs
> Update for upstream panic handler changes.

- src/lib.rs
Now that we're not running this at exit, it might as well be there if
people feel like doing it themselves.
r? @alexcrichton 
The safety is a bit interesting here - if people set a logger with set_logger_raw and the pointer didn't come from a `Box<Log>`, you can run into bad times. I would really prefer to not make `shutdown_logger` unsafe, though.
> Add a shutdown_logger function

- env/src/lib.rs
At the moment, the env logger cannot be combined with other loggers, since a) `Logger` is private, and b) logger creation and registration are combined in one function. This PR fixes those.
Fixes #85.
> Made Logger public.

- src/lib.rs
> Deprecate log_panics

- env/LICENSE-APACHE
- env/LICENSE-MIT
> Add LICENSE files to env_logger as well

- Cargo.toml
- env/Cargo.toml
Hi! [crates.io now supports categories][categories], which are a curated list
of topics aimed at helping an end-user coming to crates.io looking for
"a crate to do ______".
We're sending pull requests to selected crates to add categories in order to help 
populate the categories and seed their usefulness. We've made a guess at the best
category/categories for this crate; if it doesn't fit, please feel free to take
a look at [all the available categories and their descriptions][categories] and
[the slug values that should be specified in your Cargo.toml][slugs] and pick
different ones. If you have a category in mind that isn't available, you can
[send a PR to this file on crates.io][categories.toml] to propose additional
categories.
Crates can have up to 5 categories, and uploading …
> Add categories to Cargo.toml

- src/macros.rs
Fixes #122 
Please let me know if you want me to format the documentation differently!
Ottavio
> log! macro documentation

- src/lib.rs
> add Debug to LogMetadata and LogRecord

- Cargo.toml
> Cargo.toml badges

- Cargo.toml
> Docs link to docs.rs

- src/macros.rs
> extended example to use both patterns for log_enabled!

- src/lib.rs
> Documentation: added max_log_level per target

- src/lib.rs
fixes https://github.com/rust-lang-nursery/log/issues/130
fixes https://github.com/rust-lang-nursery/log/issues/131
> Added links to SetLoggerError and ShutdownLoggerError docs

- env/Cargo.toml
> update doc link in Cargo.toml

- src/lib.rs
Fixes #167  
Sorry, should have read the API  guideline before extending the API.
> rename error type for consistency

- src/lib.rs
- src/serde.rs
- tests/filters.rs
This is the default formatting from rustfmt 0.8.4. Closes #182.
> Run rustfmt

- src/lib.rs
> improve docs of set_logger_raw function

- src/lib.rs
Fixes https://github.com/rust-lang-nursery/log/issues/193
> Corrected header level for "Example" sections

- src/lib.rs
fixes https://github.com/rust-lang-nursery/log/issues/191
As usual my English might not be up to snuff, so I would be glad for any suggestions.
Also added link to [pretty_env_logger](https://docs.rs/pretty_env_logger/*/pretty_env_logger/) as it is one of the most popular logger sinks and my changes to its docs have been published now (related to https://github.com/rust-lang-nursery/log/issues/115).
> Toned down the references to the "frameworks"

- Cargo.toml
- src/lib.rs
> Remove deprecated panic hook

- Cargo.toml
- src/lib.rs
- src/macros.rs
> Turn __static_max_level() into a const

- .travis.yml
- src/lib.rs
> Add a secret bit of info for 0.3.x

- src/lib.rs
> Update shim for 0.4 changes

- src/lib.rs
> Some minor tweaks

- src/lib.rs
We otherwise loose the file and module info which is no good.
> Directly perform 0.3 -> 0.3 logging

- .travis.yml
- Cargo.toml
- appveyor.yml
- src/lib.rs
> Rename the use_std feature to std

- src/lib.rs
> Better documentation for filter features

- src/lib.rs
- src/macros.rs
> Make module_path, file, and line Options

- src/lib.rs
- tests/filters.rs
- tests/max_level_features/main.rs
> Remove MaxLevelFilter in favor of a simple function

- Cargo.toml
- src/lib.rs
> Bump to 0.4.0-rc.1

- src/lib.rs
> Fix max log level documentation

- README.md
- src/lib.rs
I believe shaving is a mutable operation on a yak and certainly not one multiple people should be doing unsynchronized concurrently 😇.
> Shaving mutates the yak

- README.md
> Document how to use the crate with Rust 2018

- README.md
It was a pretty tough read before ;)
> Add comma to make parsing this easier

- src/lib.rs
It is going to be deprecated in 1.50, but it's already producing
warnings on nightly.
> Remove usage of AtomicUsize::compare_exchange

- src/lib.rs
> relax ordering in `set_max_level` atomic store

- src/lib.rs
add some implement to crate doc
> add some readme to crate doc

- src/lib.rs
- tests/filters.rs
This PR just fixes up some broken links in the docs and some duplicated feature names in the filtering tests.
> Fix up some links and tests

- README.md
> docs(readme): add mention to log_err

- CHANGELOG.md
- Cargo.toml
- src/lib.rs
- src/macros.rs
- tests/macros.rs
> Prepare for 0.4.16 release

- .github/workflows/main.yml
> fix up windows targets

- README.md
- src/lib.rs
[structured-logger](https://docs.rs/structured-logger/latest/structured_logger/) is a logging implementation for the log crate that logs structured values either synchronous or asynchronous, as JSON, CBOR, or any other format, into a file, stderr, stdout, or any other destination.
> Add the structured-logger crate to the README

- src/kv/source.rs
> Remove unneeded import

- README.md
Its abstractions are as powerful as `fern` and I integrate it with a few application to see that things work well.
> Add logforth to implementation

- README.md
- src/lib.rs
> Add clang_log implementation

- CHANGELOG.md
- Cargo.toml
- src/lib.rs
* Fix up kv feature activation by @KodrAus in https://github.com/rust-lang/log/pull/659
> Prepare for 0.4.24 release
