src/lib.rs

Logger implementations sometimes need to use this to log e.g. before the
logger's finished being installed, or for testing.

Add a method to log a message to a specified logger

---

src/macros.rs

We weren't filtering in log! itself, at which point we can remove the
checks in the other macros.

Fix log filtering

---

src/lib.rs

This simple change implements and tests the `std::error::Error` trait for `log::SetLoggerError`.  This enables use of the [improved error handling](http://lucumr.pocoo.org/2014/11/6/error-handling-in-rust/) pattern and the `try!` macro.  I have tested it against my code base, which required rebuilding and testing 9 crates not my own. Examples: [rand](https://github.com/rust-lang/rand), [rustc-serialize](https://github.com/rust-lang/rustc-serialize), [rust-postgres](https://github.com/sfackler/rust-postgres), and [time](https://github.com/rust-lang/time).  Unless different `Error::description()` text is desired, it appears is good to go.

Implemented Error trait for SetLoggerError.

---

src/lib.rs

Changed LogLocation to use u32 instead of usize, according to latest changes in rust nightly, as line!() now returns a u32.

Changed LogLocation to use u32 instead of usize

---

env/src/lib.rs
src/lib.rs
src/macros.rs
tests/filters.rs

This PR contains a series of commits which add functionality and future-proofing. There are breaking changes for libraries implementing `Log` but not for libraries using the logging macros. I opened this as a PR instead of filing an issue because I think it's a bit easier to talk about when looking at an actual implementation. It deserves some discussion before merging for sure.
We may want to add to this struct in the future (maybe function name if that macro ever gets added), or replace the internals with something that extracts information from debuginfo for example. It's a bit suboptimal since we can't actually make the fields private, but I think it's good enough that we can alter the struct backwards compatibly.
I added this because it made it easier to test logger implementations, …

API overhaul round 2

---

src/lib.rs

LogLevel names are frequently output in log files and the ability to pad them to a width helps.

Respect padding for LogLevel names

---

Cargo.toml
src/lib.rs

This moves the usage of `rt::at_exit` to `libc::atexit` instead. It's not
looking like it's likely for `rt::at_exit` to be stable at 1.0, and
`libc::atexit` is at least supported on major platforms.

Remove dependence on std::rt

---

env/src/lib.rs

It is intentional that we log nothing by default, right? I can't remember ever seeing error-level logs without turning on logging but I could be misremembering.

Misc fixes

---

env/src/lib.rs

Turns out we did actually use to log errors by default!

Fix default log level

---

src/macros.rs

It's basically an implementation detail and can end up popping up in
dead code warnings if the log statement is in a dead function.
Closes #43

Disable dead code warnings for LOC static

---

README.md

This took me some trial and error to get working. 
This PR is also me asking if I'm doing this right at all... i *think* this is the best way to get log messages in tests, but I could be missing something. These make me think I'm not missing something, that this is the best way at the moment:
* https://github.com/rust-lang/log/issues/18
* https://www.reddit.com/r/rust/comments/31y66n/how_to_log_debug_in_library_tests/ctue5n0?context=10000
* http://stackoverflow.com/questions/30177845/how-to-initialize-the-logger-for-integration-tests

Add instructions and example for using env_logger in tests

---

src/macros.rs

The previous example code for the `log_enabled!` macro doesn't properly demonstrate why to use it, since the use of `log_enabled!` doesn't improve anything.  (The `debug!` macro already prevents the expensive call when debug logging is disabled.)
This changes the example to one that has better performance compared to `debug!` alone.
r? @sfackler

[docs] Use a better example for log_enabled!

---

.travis.yml
Cargo.toml
src/lib.rs
src/macros.rs
tests/max_level_features/Cargo.toml
tests/max_level_features/main.rs

This PR modifies `log!` and associated macros to disable logging at compile time for the Debug and Trace log levels when the `debug_assertions` option is disabled (which it is by default when optimizations are enabled).
The goal of this change is to make it easy to leave debug logging in place throughout a project and its dependencies, but to pay for it only in debug builds, and have it completely optimized out in release builds.
The `log_level` configuration option provides an existing way to do this. However, in practice there is no supported way to toggle `log_level` for a package *and* all of its dependencies when building with Cargo.  However, Cargo does provide per-profile options for controlling rustc's built-in `debug_assertions` option. This option is a pretty good fit for debug …

Statically disable debug logging in optimized builds

---

.travis.yml
Cargo.toml
src/lib.rs

Add a logging panic handler

---

.travis.yml
Cargo.toml
src/lib.rs
tests/filters.rs
tests/max_level_features/main.rs

Second attempt at support `no_std`, this time without splitting the crate into two. Instead, a `use_std` feature is used, which is enabled by default.
Fixes #13

Add support for no_std

---

src/lib.rs

Couple minor tweaks to stuff from use_std PR

---

env/Cargo.toml
env/src/lib.rs
env/tests/regexp_filter.rs

Regexps in RUST_LOG as explained in the module documentation should
only allow log messages that match the given expression and not the
other way around.

Fixed handling of filter regexps.

---

Cargo.toml
src/lib.rs

Windows apparently runs these after killing all other threads, so the
shutdown process can deadlock if any of those threads was logging at
that point.
Closes #74

Stop trying to drop the logger in an atexit callback

---

.travis.yml
env/Cargo.toml
env/src/lib.rs
env/src/regex.rs
env/src/string.rs

Not all uses of env-logger require a full regex engine for matching, for example
the compiler works with just simple substring matching. Additionally compiling
regex can often take quite a bit of time, so for those that would prefer the
filtering can be disabled.

Make regex an optional dependency

---

env/src/lib.rs
src/lib.rs

I'm prototyping support for pulling in crates.io crates into rustc and I believe
this'll be the support necessary for living in the sysroot.

Add ability to be used in rustc

---

README.md
env/src/lib.rs

Right now `env_logger` always logs to stderr. This might be undesireable in some cases.
This PR adds a way to configure the log target. It can be set to stdout if desired.
Note that writing to stdout is implemented with `println!` instead of `writeln!`, so that the output is properly captured in tests. See https://users.rust-lang.org/t/cargo-doesnt-capture-stderr-of-running-tests/9222/.
I did not find out how to properly add a test, but tested it manually. If you want a test to be added, pointers would be welcome.

Make log target configurable

---

src/lib.rs

Replaced my_logger with env_logger in docs

---

src/macros.rs

Added macro examples

---

src/lib.rs

Fixes #132, fixes #133 
Does it look OK?
Ottavio

LogLevel and LogLevelFilter doc improvements.

---

src/lib.rs

Linkified crate doc

---

env/src/lib.rs
src/lib.rs
src/macros.rs
tests/filters.rs
tests/max_level_features/main.rs

Fixes #142 
Types like `LogLevel` have just become `Level`.
The affected enums, structs, and functions include:
- `LogLevel`
- `LogLevelFilter`
- `LogRecord`
- `LogMetadata`
- `LogLocation`
- `MaxLogLevelFilter` (now `MaxLevelFilter`)
- `max_log_level()` (now `max_level()`)
I changed only the parts of `env_logger` that reference `log`. Should I update its types as well? (Like `LogBuilder` and `LogTarget`?)
The docs compile correctly and hyperlinking isn't broken. It's entirely possible I've missed something, but I've tried to be thorough.
Ottavio

Removed type "stuttering"

---

src/lib.rs

Add an error type to FromStr impls

---

README.md

A [recent blog post](https://techsaju.wordpress.com/2015/09/12/logging-in-rust-using-log/) shows that using the RUST_LOG variable, and the necessity of using it to get log messages other than at log level debug, isn't especially clear from the README, which is the first page people will likely end up on.

Add example usage of RUST_LOG with a pointer to the env_logger docs

---

Cargo.toml
src/lib.rs

change html_root_url

---

env/Cargo.toml
env/src/lib.rs

Closes: #141
@dtolnay there is a `documentation` line in `env/Cargo.toml` here : https://github.com/morrme/log/blob/issue141/env/Cargo.toml#L7  
Should that be updated as well?

update html_root_url for env_logger

---

Cargo.toml
env/Cargo.toml

Hi,
I've added `keywords = ["logger", "log", "logging"]` to both log and env_logger.
These are the best I could came up with.
resolves https://github.com/rust-lang-nursery/log/issues/140

Added keywords to log and env_logger Cargo.toml

---

src/lib.rs

make error description consistent with display

---

README.md
env/src/lib.rs

I did not know if private symbols LogDirective and parse_logging_spec* should also be renamed so this PR is split with private symbols in second commit.
Both unit and doc tests pass, hopefully sed did not miss anything ;)
Hi @dtolnay  is this roughly in line with what you've had in mind in https://github.com/rust-lang-nursery/log/pull/162#pullrequestreview-39892585 ?
resolves: #169

Reduce "stuttering" in env_logger symbols 

---

src/lib.rs

The example is pretty redundant (copied almost verbatim from another example).  Let me know what  I should add or remove to make this better!
Thanks!

Add more documentation to Metadata struct

---

src/lib.rs

This addresses the doc improvements suggested by [#129](https://github.com/rust-lang-nursery/log/issues/129) for the Record structure.
Let me know if there's anything missing or anything that can be improved!

Record Doc Improvements

---

src/lib.rs

This provides the doc updates as suggested in [#127](https://github.com/rust-lang-nursery/log/issues/127).
I realize I've accidentally introduced some whitespace changes; I can revert these if required.

Update docs for Location struct and add example

---

.travis.yml
Cargo.toml
appveyor.yml
src/lib.rs

Fixes #143 
Adds `serde` as an optional dependency and puts the `Serialize` and `Deserialize` traits behind `cfg_attr`. I wasn't sure what version I should specify. 1.0.7 was the latest when I checked, but maybe it's too specific? Would `>= 1.0` be better?
Saw the post on the internals forum, wanted to help out!

Add serde impls to LogLevel and LogLevelFilter

---

Cargo.toml
src/lib.rs

Pull-request for:
https://github.com/rust-lang-nursery/log/issues/143
I am not entirely sure about the format of serialization I have used.
It is also my first contribution, so any feedback is welcome.
To run tests, use:
`cargo test --features "use_serde"`
It misses documentation as of now, but I will add it before merging, I just would like some validation of the code first.

Add serde impls for LogLevel/LogLevelFilter

---

src/lib.rs

see: https://github.com/rust-lang-nursery/log/issues/134

max_level doc improvements

---

src/lib.rs

As suggested here (https://github.com/rust-lang-nursery/log/issues/135#issuecomment-304822963), it's just a kind of copy/paste of https://brson.github.io/rust-cookbook/logging.html#log-messages-with-a-custom-logger. I hope I did not miss something.
See: https://github.com/rust-lang-nursery/log/issues/135

Add example to `set_logger`

---

src/lib.rs

Has no existing issue.
Just thought it might need a link like the other items.

add link to from_str method in ParseLevelError

---

src/lib.rs

solves https://github.com/rust-lang-nursery/log/issues/115
- I've left env_logger on the list as the most popular implementation (as it is to be separated from main log repo it should not be penalized)
- I've chosen links to docs.rs over crates.io. But I do not have strong preference
- the "simple" section was a little crowded so I've pruned the least popular crates but sadly it has left us with [`simple_logger`] and [`pretty_env_logger`] which do not provide nice docs
I am eager hear any suggestions.
[`simple_logger`]: https://docs.rs/simple_logger/*/simple_logger/
[`pretty_env_logger`]: https://docs.rs/pretty_env_logger/*/pretty_env_logger/

Added links to logging frameworks

---

src/lib.rs

fixes https://github.com/rust-lang-nursery/log/issues/135

Added "Errors" section to set_logger docs

---

src/macros.rs

due to https://github.com/rust-lang-nursery/log/issues/197 this might be insufficient or even overly verbose if the actual descriptions for "Crate feature flags" would be documented thoroughly in one place. 
fixes https://github.com/rust-lang-nursery/log/issues/125

expanded log! docs for `max_level_*`

---

README.md
env/src/lib.rs
env/tests/regexp_filter.rs
src/lib.rs
tests/filters.rs
tests/max_level_features/main.rs

There might be more things to fix. But just wanted to get feedback if I am on right track!
Fix to issue #146

Change set_logger to panic on error

---

src/lib.rs

As discussed in [issue 121](https://github.com/rust-lang-nursery/log/issues/121),
The logging levels are mentioned in the use section

logging levels and corresponding macros

---

env/src/lib.rs
src/lib.rs
tests/filters.rs
tests/max_level_features/main.rs

remove shutdown and add `flush` to `Log` trait

---

env/src/lib.rs
src/lib.rs
src/macros.rs

Fixes #116.
Create builders to support the construction of `Metadata`, `Record`, and `Level`. I decided to take `mut self` as the parameter for each builder method because it allows:
```rust
let record = RecordBuilder::new().args(...).metadata(...).build()
```
Whereas taking `&mut self` leads to the temporary object created by `RecordBuilder::new()` being dropped before `build()`.
Not done yet--still need to add examples/docs. Please review everything else!

Create builders for `Metadata`, `Record`, and `Level`.

---

src/lib.rs
src/macros.rs

They now take a `&Record` and `&Metadata` respectively. Shim libraries
from other logging frameworks will want to construct these types
directly rather than using the log macros.
r? @alexcrichton 
Disassembly of --release optimized
```rust
#[macro_use]
extern crate log;
fn main() {
debug!("hello world!");
}
```
Before:
```asm
00000000000068b0 <_ZN3foo4main17h1780161ba875bb72E>:
68b0:       48 83 ec 38             sub    $0x38,%rsp
68b4:       48 8d 05 75 7b 24 00    lea    0x247b75(%rip),%rax        # 24e430 <_ZN3log20MAX_LOG_LEVEL_FILTER17h69a143a1bb28dbc7E>                                                                                                                 
68bb:       48 8b 00                mov    (%rax),%rax …
```

Make __log and __enabled public

---

src/lib.rs
src/macros.rs

We also have flush on the Log trait, and at that point it makes more
sense to just return the logger directly.

Replace log and enabled functions with logger

---

src/lib.rs
tests/filters.rs
tests/max_level_features/main.rs

Rename set_logger_raw to try_set_logger_raw

---

src/lib.rs

Closes #206
Closes #94 
We won't be able forward these values to an 0.3 logger but that doesn't seem like the end of the world. The other direction (libraries using 0.3 to log to an 0.4 logger) is the one that matters way more.

Don't force module_path and file strings to be static

---

src/lib.rs

This allows us to make try_set_logger_raw a safe function. It turns out
that every example dealing with that function was violating the static
lifetime requirement. Fun!

Use a &'static Log rather than raw pointer

---

.travis.yml
Cargo.toml
appveyor.yml
src/lib.rs
tests/filters.rs
tests/max_level_features/main.rs

try_set_logger_raw is now set_logger and try_set_logger is now
set_boxed_logger. The use_std feature is now disabled by default. The
old set_logger has been removed.
When we did the crate evaluation for log, we wanted to add more variants
of set_logger that e.g. panicked by default, but I'm no longer convinced
that's a good idea. There are going to be very few instances of actually
calling these methods explicitly, since each logger implementation
should be providing their own init method that calls them. Having a huge
constellation of functions that all do basically the same thing just
makes things really confusing. We also don't want to encourage logger
implementations to only provide an init function that panics because a
common way of working with logging in tests is to try to init …

Restructure initialization setup

---

src/lib.rs
src/macros.rs
src/serde.rs

It makes more sense to centrally locate that information.
Also run rustfmt.

Remove static log config info from macro docs

---

.travis.yml

We want to know if we're dropping support for old releases.

Explicitly test against 1.16.0

---

CHANGELOG.md
Cargo.toml
src/lib.rs

I don't know if this release needs a `CHANGELOG.md` entry, but if that is the case, I will be happy to add one.
This release is needed to unblock rust-lang/rust#46278.

Fix broken links and bump the version to 0.4.1

---

README.md

I'm not affiliated with the crate, but I think it's an interesting addition because it shows that logging can also be done cleanly on platforms like Android, not just on regular Linux.

List android_log crate in README

---

src/serde.rs

This is required by some deserializers which deserialize identifiers using their binary representation. An example of one such serializer is [Ron](https://github.com/ron-rs/ron/blob/a5a4b2ee21f5be0b07c55844e2689ae8a521da3b/src/de/mod.rs#L441-L446).
This implementation should be equivalent to what serde derive would [implement for enum variants](https://github.com/serde-rs/serde/blob/5efb22ebee128f1ec4a755556230bdd66c3f2026/serde_derive/src/de.rs#L2084-L2097).

Level and LevelFilter can now be deserialized from byte slices

---

src/lib.rs

I had difficulty figuring out why I couldn't get `serde` support, until I figured out that I was missing a feature flag in my `Cargo.toml`. This PR addresses that issue for others by adding a short section to the crate's docs about it.
Please make suggestions and comments, so that we can make rust's documentation even better!

Added Crate Feature Flags Documentation

---

src/lib.rs
src/macros.rs

The extra work involved in loading the logger and creating the record
struct involves move codegen than is necessary if we take this kind of
approach (which we previously used in 0.3). It's a bit unfortunate to
have these public-but-not-public functions, but I think it's worth it.
We want to minimize the footprint of logging so people feel comfortable
using it!
A main function containing nothing but `warn!("hello world")` shrinks
from 204 bytes to 124 bytes in x86_64 with this change.
Closes #275

Optimize logging codegen

---

src/lib.rs
src/macros.rs

I had a look at #276 and thought I could do better!
There basically two areas where an improvement can be found:
- LLVM generates pretty poor code for the default implementations of `PartialOrd::{lt,le,gt,ge}` which forward to `partial_cmp`. So I added versions which perform the desired comparison directly.
- The target and location are almost always compile-time constants and can be passed in as a single argument which points to a static constant. This unfortunately doesn't work for the log level since we first need to make a local copy of it so that it is only evaluated once.
A main function containing nothing but `warn!("hello world")` shrinks from 160 bytes to 98 bytes in x86_64 with this change.

Further optimize code size

---

src/lib.rs

Two changes:
1) fixed the mistake in the example: `release_max_level_warn` disables `trace`, `debug`, and `info`, not `trace`, `info`, and `warn`.
2) The explanation of log levels was a bit misleading because it was said that `error!` represents the *highest-priority log level*. However, the *log level* that shows only `error` is the *lowest*. I removed the word level there, and added additional explanation about log levels as *the level of verbosity*.

Elaborated documentation around log levels.

---

src/lib.rs

If `set_logger_inner` is called while `STATE` is `INITIALIZING`, make it wait until the `STATE` is `INITIALIZED` so that callers can assume that the logging state is fully initialized after a call to `set_logger_inner`.
Note that this is a very simple implementation which could deadlock if `make_logger()` calls back into `set_logger_inner`, but that shouldn't happen since log's documentation says that `set_logger` should only be called once. If this is a concern, a more complex implementation that avoids this problem would be possible.
Fixes #286.

Ensure that initialization is complete after `set_logger_inner`.

---

src/macros.rs

This fixes the following error when using Rust 2018 style macro imports.
```rust
use log::info;
fn main() {
info!("...");
}
```
```console
error: cannot find macro `log!` in this scope
--> src/main.rs:4:5
|
4 |     info!("...");
|     ^^^^^^^^^^^^^
```
The `local_inner_macros` modifier resolves all macro invocations made from within that macro as macros in the same crate. So if `info!` expands to an invocation of `log!` then this would be resolved as `$crate::log!` rather than requiring the caller to have `log` in scope.
The attribute is ignored by pre-2018 compilers so log will continue to work as normal with #[macro_use].
In the future when dropping compatibility with pre-2018 compilers we can remove the `local_inner_macros` modifier and use our own explicit `$crate::` prefixes on …

Use local_inner_macros to resolve all local macros within $crate

---

src/macros.rs

One example in the saltyrtc-client repository uses `log_line` as the name of a macro, causing https://github.com/rust-lang-nursery/log/issues/291 since they perform a glob import of all macros from `log`.
https://github.com/saltyrtc/saltyrtc-client-rs/blob/9ecc88c0fe/examples/chat/main.rs#L353

Make private helper macro names less likely to conflict

---

src/macros.rs

Fixes #300 
It seems that PR #288 missed to mark the `log_enabled` macro as `local_inner_macros`. This PR should hopefully make it possible to fully use this crate with the new way of importing macros.

Fix so log_enabled can be used without #[macro_use]

---

README.md

Just expands on what _Rust 2018_ is in the readme to avoid possible confusion. This came up in #298

Clarify what 2018 edition is a bit

---

src/lib.rs

For #309 
Adds a note to the crate docs to discourage libraries from using the max level features.
@sfackler does this look ok to you?

Add a note to avoid setting max levels

---

README.md

Closes rust-lang-nursery#252
Just calls out the explicit version of rustc that we test against in CI, along with a policy for how we'll change it. I copied it from lazy-static.
cc @sfackler are you on board with this? Or would you prefer something different?

Add minimum version policy to readme

---

src/lib.rs

Silence deprecation warning for ATOMIC_USIZE_INIT

---

src/macros.rs

The `log!` macro matches part of its arguments as `$($arg:tt)+`, but the other macros match it as `$($arg:tt)*`. That means if a user calls `error!()` or any of the other macros with an empty argument, it successfully matches the macro rules of the first macro they called but then turns into an invalid call to `log!`, leading to a confusing error message.
This PR uses `$($arg:tt)+` consistently to match arguments.
```rust
use log::error;
fn main() {
error!();
}
```
```console
error: expected identifier, found `,`
--> src/main.rs:4:5
|
4 |     error!();
|     ^^^^^^^^^
|     |
|     expected identifier
|     help: remove this comma
|
= note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)
```
```console …
```

Improve error when missing macro argument

---

.travis.yml
Cargo.toml
build.rs
src/lib.rs

As discussed in https://github.com/rust-lang-nursery/log/issues/285, this adds another initialization function, `set_logger_racy`, which doesn't use `compare_and_swap` and is unsafe.
This allows `log` to support platforms that lack CAS support, which includes `thumbv6`. I haven't added any other architecture since I don't know how the exact support matrix for atomics looks.
Closes https://github.com/rust-lang-nursery/log/issues/285

Thumbv6 support

---

src/kv/source.rs

Adds a `Source::count(&self) -> usize` method to figure out how many key-value pairs to expect.
I've also tried to clarify the expectation that subsequent calls to `Source::visit` will yield the same key-value pairs unless the visitor fails. A buggy `Source::visit` with the default implementation of `count` may yield a different number of key-value pairs. Given that, we could make the method something like `Source::size_hint(&self) -> Option<usize>` instead, but I think the fundamental requirement that `Source::visit` passes the same pairs to the visitor unless the visitor itself fails is reasonable and lets us add more useful methods like `for_each` that don't have to return results. The reason `visit` itself is fallible is so that a formatting or serialization error can be passed …

Add a count method to Source

---

src/lib.rs

This mirrors a similar commit fe073054a0999d1bb238cb0293757741e95b3588
that changed output for Level, it seems sensible if the user wishes to
output the logging filter level to afford the same formatting choices.

Respect padding for LevelFilter Display

---

src/kv/source.rs
src/kv/value/impls.rs
src/kv/value/mod.rs
src/kv/value/test.rs

Part of #149
Adds `get` to `Source` for fetching a single value:
```rust
fn get<'v>(&'v self, key: Key) -> Option<Value<'v>> { .. }
```
It's useful for cases where you want to find 'well-known' key values like timestamps, errors, trace ids etc.
The method needs to be object-safe, so it takes a concrete `Key` instead of a generic type. It could take a `&dyn ToKey` instead, which could have nicer ergonomics, but I opted for the simpler API to start with.
The method has a default implementation that has a O(N) cost. It will always look at all key-value pairs. Implementations for types like maps or concrete structs can override this to be more efficient. For implementations that we own we could use the `Result` to early return when a match is found instead of continuing to look for a match. …

Add a Source::get method for finding a single value

---

src/kv/error.rs

And keep the original error, so that an io error inside the visitor is
returned accessible by the call to `visit`.
I started working on adding kv support to envlogger, and found that with the current implementation of kv::Error, it isn't possible to keep information about io errors from inside the visitor.

Add conversion to/from io::Error for kv::Error

---

README.md

This is a follow-up for changes 0da424552703 and 0f3ffb9d051c.

Remove duplicate Rust 2018 documentation

---

src/kv/mod.rs
src/kv/source.rs
src/kv/value/impls.rs
src/kv/value/internal.rs
src/kv/value/mod.rs
src/kv/value/test.rs
src/lib.rs

This PR allows consumers to work around `Value`'s required lifetime constraints in two ways:
1. allowing us to create a value with any lifetime from some owned primitive, like u8, bool etc. This is what the `Primitive` type is all about.
2. allowing us to create a value from some type that _can_ produce a concrete value we can use, but doesn't guarantee it will live as long as the value itself. This is what the `Fill` and `Slot` types are all about.
The `Fill` API is a more advanced initialization strategy (it's _actually_ a kind of visitor that just tries very hard to look like initialization), so it isn't exported from the `log::kv` module. Instead, this PR makes the `value` module public and leaves `Fill` and `Slot` in there. We need something like this to be able to translate a `&'kvs …

Make it easier to create a Value from owned or erased external types

---

CHANGELOG.md
Cargo.toml
src/kv/mod.rs
src/lib.rs

[Current changeset since `0.4.6`](https://github.com/rust-lang-nursery/log/compare/0.4.6...master)
It's been a while since we've done a release and there's a few things sitting on `master` that people want to be able to use.
I've added a note to our current structured logging stuff so it's clear that we're not committing to exactly what's there stability-wise. There are hoops we could make users jump through to access that API besides an unstable feature gate, but that didn't seem really necessary to me.

Prepare for 0.4.7 release

---

.travis.yml
Cargo.toml
src/kv/error.rs
src/kv/value/impls.rs
src/kv/value/internal.rs
src/kv/value/mod.rs
src/kv/value/test.rs
src/lib.rs

This PR adds a new unstable feature for structured logging that lets consumers actually interact with the structure of values.
It doesn't do this by exposing its own serialization contract. Instead, it implements traits from a serialization framework called `sval`. I'm open to any philosophical debate on different approaches here!
There are two commits that I think demonstrate how it fits together:
- [Refactor `value` internals so we can add in-band serialization frameworks easily.](https://github.com/rust-lang-nursery/log/commit/15ccf07784fd831adbc2a2b29e78e382c4bbae79)
- [Add `sval` support](https://github.com/rust-lang-nursery/log/commit/06beb05c422e077e51b1f7a1c7b05f01a16885f6). This is the one to look at if you're interested in what impact introducing in-band frameworks has.
[`sval` …

Add structured support to kv::Value using sval

---

src/lib.rs

Logger implementations commonly need to convert a `Record` into a
non-borrowed form to e.g. log it asynchronously on a separate thread.
This allows them to avoid having to allocate owned `String`s for the
module path and file fields, which will in practice almost always be
`'static`.
cc #206
r? @KodrAus

Dynamically track the 'static-ness of record strings

---

CHANGELOG.md
Cargo.toml
src/lib.rs

[Current changeset since the last release](https://github.com/rust-lang-nursery/log/compare/0.4.7...master)
There's only one new publicly visible and stable change since `0.4.7`: https://github.com/rust-lang-nursery/log/pull/344

prepare for 0.4.8 release

---

src/lib.rs

Fix documentation for static max_level_xxx filters

---

src/kv/mod.rs

This inlines the docs for all `kv::value` subtypes which should make it easier to read & dicscover. Thanks!
_edit: a few lines have been shuffled around because rustfmt ran from my editor. Hope that's okay!_

inline docs for kv::value

---

.github/workflows/main.yml
Cargo.toml
README.md
src/lib.rs

Use explicit version of cfg-if in msrv build

---

Cargo.toml
src/lib.rs
src/macros.rs
tests/macros.rs

Adds key-value support to the log macros. Supersedes #346. Refs #343 #328. Thanks!
```rust
femme::start(log::LevelFilter::Info).unwrap();
info!("hello");
info!("hello",);
info!("hello {}", "cats");
info!("hello {}", "cats",);
info!("hello {}", "cats", {
cat_1: "chashu",
cat_2: "nori",
});
```

kv macro support

---

src/lib.rs
src/macros.rs

This cuts the size of
```rust
fn main() {
log::warn!("hello world");
}
```
from 95 bytes:
```asm
00000000000042f0 <_ZN3foo4main17h91a1e0cbbd2d1746E>:
42f0:       48 83 ec 38             sub    $0x38,%rsp
42f4:       48 8d 05 55 dd 02 00    lea    0x2dd55(%rip),%rax        # 32050 <_ZN3log20MAX_LOG_LEVEL_FILTER17h8b54f41fea648f5cE>
42fb:       48 8b 00                mov    (%rax),%rax
42fe:       48 83 f8 03             cmp    $0x3,%rax
4302:       72 47                   jb     434b <_ZN3foo4main17h91a1e0cbbd2d1746E+0x5b>
4304:       48 8d 05 1d bd 02 00    lea    0x2bd1d(%rip),%rax        # 30028 <anon.7cf0325160a81106a62a3eb77a18e0e0.0.llvm.16433780892884680004+0x30>
430b:       48 89 44 24 08          mov    %rax,0x8(%rsp)
4310:       48 c7 44 24 10 01 00    movq   $0x1,0x10(%rsp) …
```

Add a separate path for messages with no format arguments

---

src/kv/error.rs
src/kv/source.rs
src/kv/value/internal.rs
src/kv/value/mod.rs
src/kv/value/test.rs
src/lib.rs
test_max_level_features/main.rs
tests/filters.rs

Since the minimum supported rustc version was bumped in #362, it is now possible to do some cleanup.
* Get rid of a re-implementation of `Box::leak`. This reduces the number of unsafe blocks to 4.
* Run `cargo fix` to add the `dyn` keyword to a lot of types.
* Remove a few instances of the `'static` lifetime in some static items.

Miscellaneous cleanup

---

CHANGELOG.md
Cargo.toml
src/lib.rs

[Changeset since the last release](https://github.com/rust-lang/log/compare/0.4.8...master)
**Minimum supported `rustc` is being bumped to `1.31.0`.** This release is just over 12 months old now.
Includes:
- #347
- #349 
- #352
- #354
- #362
- #353
- #366
- #367
This release includes some macro support for our experimental structured logging, which could use some more eyes to make sure we're not missing anything important.
cc @wycats 
r? @sfackler @dtolnay @BurntSushi

Prepare for 0.4.9 release

---

src/macros.rs
tests/macros.rs

Fixes #369
Also adds some test coverage for `log!` macros in expression context, which regressed between `0.4.8` and `0.4.9`.
r? @sfackler

fix up macro use in expr context

---

CHANGELOG.md
Cargo.toml
src/lib.rs
src/macros.rs

Includes #370 
I've also just made our macro syntax consistent so we can see matches that are terminal vs matches that just expand to other matches.
r? @sfackler

Prepare for 0.4.10 release

---

src/kv/error.rs
src/lib.rs

`Error::description` has been documented as soft-deprecated since 1.27.0 (17 months ago). It is going to be hard-deprecated soon.
This PR:
- Removes all implementations of `description` in all error types
Related PR: https://github.com/rust-lang/rust/pull/66919

Remove deprecated Error::description

---

src/lib.rs
src/macros.rs
tests/macros.rs

In #369 and #372 we've run into a few regressions with the new macro implementation that supports key-value pairs. This PR shifts that implementation onto a new branch called [`kv_macro`](https://github.com/rust-lang/log/tree/kv_macro) so that we can work on it out-of-band.
cc @yoshuawuyts
r? @sfackler

Revert the macro implementation

---

src/lib.rs

MSRV is now high enough that AtomicUsize::new is available

Remove ATOMIC_USIZE_INIT

---

README.md

The current crate description on crates.io shows a failing build (pointed at `alexcrichton/log` on AppVeyor); checking back here to the README I couldn't easily see where builds are happening now, hence this PR. HTH!

Show master branch build status in README

---

src/lib.rs

This removes the `mem::transmute` in `max_level` in favor of an explicit match.
Previously, the `LevelFilter` had `#[repr(usize)]`. `set_max_level` would call `level as usize` and `max_level` would use `transmute::<usize, LevelFilter>`. This does not seem to be defined behavior - although `repr(usize)` [guarantees that `LevelFilter` will be represented as a `usize`](https://doc.rust-lang.org/nomicon/other-reprs.html#repru-repri), it does not guarantee that every `usize` is a valid `LevelFilter`.
Furthermore, although in practice `as usize` will return 0, 1, ... for the enum variants, this is not guaranteed by the compiler, even though [other parts of the code depend on this](https://github.com/rust-lang/log/compare/master...jyn514:master#diff-b4aea3e418ccdb71239b96952d9cddb6L334).
This …

Document use of mem::transmute

---

README.md

win_dbg_logger is logger for use with Windows debuggers.
Windows allows applications to output a string directly to debuggers. This is
very useful in situations where other forms of logging are not available.
For example, stderr is not available for GUI apps.
This crate can be compiled and used on non-Windows platforms, but it does
nothing. This is intended to minimize the impact on code that takes a
dependency on this crate.

Add reference to win_dbg_logger

---

src/kv/error.rs
src/kv/value/internal/fmt.rs
src/lib.rs

This impl breaks some code in rust-analyzer's ra_hir_def crate.
https://github.com/rust-analyzer/rust-analyzer/blob/1dba84019e0f3e7175f204624629a52013332e52/crates/ra_hir_def/src/path.rs#L273-L307
```console
$ cargo check --manifest-path crates/ra_hir_def/Cargo.toml
Checking ra_hir_def v0.1.0
Finished dev [unoptimized] target(s) in 0.75s
$ cargo check --manifest-path crates/ra_hir_def/Cargo.toml --features log/kv_unstable
Checking ra_hir_def v0.1.0
error[E0282]: type annotations needed for the closure `fn(&str) -> std::result::Result<(), _>`
--> crates/ra_hir_def/src/path.rs:278:17
|
278 |                 f.write_str("::")?;
|                 ^^^^^^^^^^^^^^^^^^ cannot infer type
|
help: give this closure an explicit return type without `_` placeholders
|
276 |         let mut add_segment …
```

Resolve possible inference disruption by removing unneeded From impl

---

Cargo.toml
src/kv/error.rs
src/kv/value/fill.rs
src/kv/value/impls.rs
src/kv/value/internal/fmt.rs
src/kv/value/internal/sval.rs

Fixes #395 
This PR makes the `fmt::Debug` and `fmt::Display` impls on `Value` respect the trait being used and any flags present. I've added a separate visitor for `Display` that uses the right trait, and pass the value directly to the formatter instead of going through `format_args`.
There are some extra tests for formatting and I've shifted a few pieces around to be consistent. ~~Tests won't pass until I fix https://github.com/sval-rs/sval/issues/84 as well.~~
r? @yoshuawuyts

Respect fmt trait and flags in Value

---

.github/workflows/main.yml
CHANGELOG.md
Cargo.toml
src/lib.rs

[Changes since the last release](https://github.com/rust-lang/log/compare/0.4.10...master)
Includes:
- https://github.com/rust-lang/log/pull/373
- https://github.com/rust-lang/log/pull/374
- https://github.com/rust-lang/log/pull/377
- https://github.com/rust-lang/log/pull/379
- https://github.com/rust-lang/log/pull/380
- https://github.com/rust-lang/log/pull/384
- https://github.com/rust-lang/log/pull/392
- https://github.com/rust-lang/log/pull/393
- https://github.com/rust-lang/log/pull/398
- https://github.com/rust-lang/log/pull/400
Most of the new code is in the unstable `kv` module.

Prepare for 0.4.11 release

---

src/serde.rs

This PR allows the Level and LevelFilter enums to deserialize from the index_variant.
This solves https://github.com/jamesmunns/postcard/issues/24.
Postcard is made to serialize into a compact byte representation, so it takes the index_variant that is provided by the [Serialize implementation](https://github.com/rust-lang/log/blob/master/src/serde.rs#L23). There was however no way to change that back into the enum.

Allow Level and LevelFilter to deserialize from the index_variant

---

src/kv/source.rs

This just makes sure we don't forget to forward Source methods on types that wrap other sources by forcing all methods to be implemented when running tests.

Require Source methods be implemented in test

---

src/lib.rs

Returns the string representation of the `Level`.

Add Level::as_str

---

src/lib.rs

Hi there! I was trying to wrap a `Box<dyn Log>` returned from [flexi logger](https://docs.rs/flexi_logger/0.16.1/flexi_logger/struct.Logger.html#method.build) into [async_log](https://docs.rs/async-log/2.0.0/async_log/struct.Logger.html#method.wrap) but I was unable to do so since the `Log` trait was not implemented for `Box<dyn Log>`.
One option was to create a wrapper struct:
```
struct LoggerWrapper(Box<dyn Log>);
impl Log for LoggerWrapper {
fn enabled(&self, metadata: &Metadata) -> bool {
self.0.enabled(metadata)
}
fn log(&self, record: &Record) {
self.0.log(record)
}
fn flush(&self) {
self.0.flush();
}
}
```
It was suggested to me that it might be beneficial to have the implementation in the log crate so I've added the implementation in this pull request. 
Would you accept this …

Implement Log for Box<Log>

---

.github/workflows/main.yml
build.rs
src/lib.rs

Some targets (such as RV32IMC) don't have atomic support. This PR allows the log crate to build for those targets.
As the platform doesn't have atomics we can't implement an Atomic version of AtomicUsize, so this version is not atomic. Any platform without atomics is unlikely to have multiple cores, so this shouldn't be a problem.
This is somewhat based on implementations in: https://github.com/japaric/heapless

atomics: Add support for targets without atomics

---

build.rs

We were going to depend on `const_type_id`, but that feature was reverted before it was stabilized.
I'm working on a refactoring that changes this, but in the meantime anybody depending on `kv_unstable` and building on `1.47.0` is broken. This just removes the expectation that `1.47.0` will allow `const_type_id`.

remove dependency on reverted const type id

---

Cargo.toml
src/kv/key.rs
src/kv/mod.rs
src/kv/source.rs
src/kv/value.rs

This PR does two things:
- Exposes the `Value::downcast_ref` method that was missed in #423 
- Adds adapters so that `Source`s can be treated like a map or sequence for formatting or serialization
This means `Log` implementors can now write something like:
```rust
use log::kv::source;
#[derive(Serialize)]
pub struct MyRecordAsMap<'a> {
msg: &'a str,
#[serde(flatten)]
#[serde(with = "source::as_map")]
kvs: &'a dyn Source,
}
```
to define a type that can be serialized using `serde` as a map with key values flattened.

Key-value serializer adapters

---

src/macros.rs

This will allow these macros to continue to be used in expression
position if https://github.com/rust-lang/rust/issues/33953 is fixed.

Remove some trailing semicolons from macro definitions

---

CHANGELOG.md
Cargo.toml
src/lib.rs

Changes since last release: https://github.com/rust-lang/log/compare/0.4.11...master
This includes patches:
- #405
- #409
- #414
- #413 
- #422 
- #427 
Changes to `log`'s dependencies:
- #417 
Changes to the unstable structured logging API:
- #396
- #406
- #419 
- #418 
- #423 
- #426

Prepare for 0.4.12 release

---

Cargo.toml

Without including the path, `cargo test` would work, but `cargo package` would fail.

Add path for filters and macros tests

---

.github/workflows/main.yml
src/kv/value.rs

Closes #433 
There's an incorrect `#[cfg(feature = "std")]` in `kv::value` that's broken users upgrading to `0.4.12`. This PR fixes that up and runs a few more permutations in CI.

check std feature against kv_unstable

---

CHANGELOG.md
Cargo.toml
src/lib.rs

cc @fggarcia @Byron
This includes #434, which was a bug when a combination of `kv_unstable` and `std` features was enabled in `log`.

Prepare for 0.4.13 release

---

CHANGELOG.md
Cargo.toml
src/lib.rs

For #437 
This creates a patch release from `0.4.11` with an additional `kv_unstable_std` feature. I'm going to PR repositories that are currently depending on `kv_unstable` and `std` and this patch release will minimize any disruption caused by the change in features in the meantime.
What's currently `0.4.13` will now become `0.4.14`.

Prepare for 0.4.13 release patch

---

CHANGELOG.md

For #437 
This reflects the way `0.4.13` is being patch released in #441 in the changelog so it's possible to follow the trail.

Update changelog to reflect 0.4.13 patch

---

src/lib.rs
src/macros.rs

https://github.com/rust-lang/log/issues/445#issuecomment-765965279:
> That special case existed to minimize the amount of code generated, but it's not compatible with format_args_capture as you pointed out. It should just be removed.
Closes #445.
I did not add a test for `format_args_capture`. I think I need to create a custom logger to capture records and add a testing-only crate feature or `--cfg` (to tell if `#![feature(format_args_capture)]` is allowed to use) to test it. `format_args_capture` is *unstable* now, I'm not sure if it worths it. Feel free to ask me to add such test if it's necessary.

Remove the `__private_api_log_lit` special case

---

CHANGELOG.md
Cargo.toml
src/kv/value.rs
src/lib.rs

Updating our unstable key-value API based on changes to `value-bag`.

Prepare for.0.4.14 release

---

src/lib.rs
src/macros.rs
tests/macros.rs

Attempt number two/three? Too many in any case.
Previously I proposed a design that followed a `struct` like syntax:
```rust
info!("my message: {}", arg, {
key1: "value1",
key2: 123,
});
```
However it turns out that this does not work well with named arguments
as reported in issues #369 and #372. The implementation was eventually
reverted in pr #374.
This new design takes inspiration from the `tracing` crate which already
supports key-value pairs in logging events. The basic idea is to put the
key-value pairs before the message and arguments. Applying the same
structure like syntax as above we would get something like the
following.
```rust
info!({
key1: "value1",
key2: 123,
}, "my message: {}", arg);
```
But personally I'm not a big fan of this formatting, let's try putting
everything …

Add key-values to the macros

---

src/lib.rs

It was not clear whether `error` or `trace` was the maximum log level.
The docs said "`error!` represents the _highest_-priority log messages and `trace!` the _lowest_".
Yet, `set_max_level` regards `Trace` to be the maximum level.
I attempted to clarify this by avoiding the terms "high" and "low" in the docs except for where
they are applicable to the Rust order as defined in `Ord`.
I spent about 30 minutes being confused by this. It seemed to me that `set_max_level` would be used to filter errors and warnings while emitting debug messages, which confused me.
I was going to create an issue first, but decided I would update the docs myself as an initial proposal of how to improve them, so I have created this PR instead.

Clarify ordering of log levels in the docs

---

src/kv/error.rs
src/kv/value.rs

Closes #440
This surfaces a zero-dependency visitor for `kv::Value`s that can be used instead of having to chain `to_*` calls when a full serialization framework like `serde` isn't needed.
r? @Thomasdezeeuw

Add a simple zero-dependency visitor for kv values

---

src/lib.rs

I am using `FromStr` implementation of `LevelFilter` to parse logging level given by user via command line flag. In case user gives invalid logging level I want to print list of allowed values. Currently I have to replicate `LOG_LEVEL_NAMES` array in my code and remember to keep it in sync (It is probably unlikely it changes that much though).
One question I have is that is there a reason it is `static` instead of `const`?

Expose logging levels 

---

src/lib.rs

Follow up to #459 
Adds some doc tests for iterating over levels and filters and fixes up an infinite loop in the implementation.

Fix up level iterators

---

README.md

Closes #421
We don't expose a C API for the `log` crate, so this is just to leave a breadcrumb for anybody wanting to log across dynamically loaded libraries.

Add a note about use in dynamic libraries

---

.github/workflows/main.yml
tests/filters.rs

Closes #381
The filtering tests don't really make sense in the presence of static max level filters. This PR just no-ops them when any of these is enabled. That way we still run them with the default `cargo test`, but make it possible to also run `cargo test --all-features`.

Fix tests when running with --all-features

---

src/lib.rs

Closes #458. Turns out that `Rc<Log>` isn't possible because `Log: Sync`. Other candidates for adding:
- `Cow`
- `Option`
- `()` (this would allow us to get rid of the internal `NopLogger`)
- `Pin` (?)
- Probably forgot something

Add Log implementation for &impl Log and Arc<impl Log>

---

Cargo.toml
README.md
src/kv/value.rs
src/lib.rs
src/macros.rs
tests/Cargo.toml
tests/macros.rs

Part of #436 
This tweaks the new key-value macro syntax slightly so that it can be more consistent in cases where key-values are supplied and in cases where they're not. All the old syntax is still supported, but we can now write `log!` macros like:
```rust
info!(target = "my_target"; "format {string}");
```
which then supports key-value pairs as:
```rust
info!(target = "my_target"; key1 = value1, key2 = value2; "format {formatted1}", formatted1 = value1);
```
For key-values, the `target = x;` form is required. It splits our macro up into 3 logical parts, separated by `;`s:
1. `target = "my_target"`: The portion of the log record that's considered by top-level filtering. It's equivalent to `log_enabled!`.
2. `key1 = value1, key2 = value2`: The structured data associated with the log …

Allow macros to be more consistent with kvs

---

Cargo.toml

These files were removed in #354.

Remove outdated Travis CI and AppVeyor references

---

CHANGELOG.md
Cargo.toml
src/lib.rs

[Changes since the last release](https://github.com/rust-lang/log/compare/0.4.14...HEAD)
This includes:
- #454 
- #449 
- #465 
- #464 
- #463 
- #461 
- #420 
- #467 
- #459 
- #468 
- #469 
- #470 
- #471 
- #473 
- #475 
- #476 
- #479 
- #478 
- #482 
- #483

Prepare for 0.4.15 release

---

src/kv/value.rs

It can already by be done by calling `.get()`, but this makes it a bit
easier.

Implement ToValue and From<$ty> for Value for NonZero

---

README.md
src/lib.rs

db_logger is a logging implementation that writes log entries to a
database.  At the time of this writing, it supports PostgreSQL and
SQLite via the sqlx crate.

Add reference to db_logger

---

Cargo.toml
src/kv/value.rs
tests/macros.rs

This PR upgrades our `value-bag` version to `1.0.0-alpha.9`, which includes a breaking change to how 128bit numbers are handled. Instead of storing them by-value we only store them by reference. Along with some other internal layout changes this reduces the size of `Value` from 48 to 24 bytes, which is a great saving for the stack-local arrays we create to hold them.
In practice this doesn't affect whether or not 128bit values can be used in the macros because they rely on the `ToValue` trait, which is always by-reference. I'd be keen to hear if anybody is relying on the `From` impls though.
I'm hoping to get this through sooner rather than later in case https://github.com/rust-lang/rust/pull/95845 is merged in its current state that breaks constant type id comparison, which will mean …

Upgrade to value-bag 1.0.0-alpha.9 and remove by-value 128bit int conversions

---

src/lib.rs

Closes #472
This just notes that implementors of the `Log` trait should call their own `enabled` function somewhere in their `log` implementation to apply filtering.

Note that Log implementors should call enabled

---

CHANGELOG.md
Cargo.toml
src/lib.rs

[Changes since the last release](https://github.com/rust-lang/log/compare/3cc17c1c4f...master)
Includes:
- #502 
- #504 
- #505 
- #506

Prepare for 0.4.17 release

---

.github/workflows/main.yml

As request in https://github.com/rust-lang/log/pull/513#issuecomment-1141933776 by @KodrAus ;)
In can be seen in action here: https://github.com/hellow554/log/runs/6669579058?check_suite_focus=true

add cargo doc to workflow

---

src/lib.rs

The latter has been available since rust 1.23.0.

Replace ad-hoc eq_ignore_ascii_case with slice::eq_ignore_ascii_case

---

Cargo.toml
src/lib.rs

`cfg_if` is only used in a single place and seems a bit redundant.
log is such a depended upon library I feel like removing even the smallest dependency is a win

Remove dependency on cfg_if

---

README.md
src/lib.rs

Add links to compatible  [call_logger](https://docs.rs/call_logger/0.0.2/call_logger/) to the README and rustdoc documentation

Add call_logger to the documentation

---

README.md

Change wording of list of implementations

---

README.md

While making https://github.com/rust-lang/log/pull/553 I released my own library isn't even in the list, so I though I might as well add it. Unless we decide to remove all of them in https://github.com/rust-lang/log/issues/551.

Add std-logger to list of implementations

---

src/lib.rs

Calling `set_max_level` can result in a race condition on platforms that don't have an atomic compare and swap implementation. This gates `set_max_level` behind `#[cfg(atomic_cas)]` and adds a racy alternative that can be called in these situations. This mirrors the approach for `set_logger`.
Fixes #534

Add `set_max_level_racy` and gate `set_max_level`

---

src/lib.rs

Fixes up the build after #544 since we refactored our atomic cfgs in #543.

Use target_has_atomic instead of the old atomic_cas cfg

---

src/lib.rs

unused variable: `metadata`,  according to rustc, 
if this is intentional, prefix it with an underscore: `_metadata`

[doc] src/lib.rs : prefix an unused variable with an underscore

---

src/macros.rs

[doc] src/macros.rs :  correct  grammar errors of an example in lib documentation

---

.github/workflows/main.yml
Cargo.toml
build.rs
src/lib.rs

For #564
This is already fixed on the `master` branch, but we committed not to release that until the next stable version of Debian. In the meantime, this reverts #543 so we can get a patch out that still targets `rustc` `1.31.0`. Once that is released, I'll revert this commit so #552 will still include it.

Revert MSRV bump for patch release

---

CHANGELOG.md
Cargo.toml
src/lib.rs

Closes #564 
This is a patch release of #552 without the MSRV bump.

Prepare for 0.4.18 release

---

Cargo.toml
tests/macros.rs

Remove rustversion dev-dependency

---

src/lib.rs
src/macros.rs

Since we have dropped support for pre-1.30 compilers.

Remove `local_inner_macros` usage

---

src/__private_api.rs
src/lib.rs
src/macros.rs

This is the first step of bring optimizations from #569 into the `log` crate.
This PR contains two commits:
- The first commit moves all private APIs into a single `__private_api` module so that it is easier to implement more elaborated optimizations.
- The second commit splits `&(target, module_path, file, line)` argument into two arguments: `&(target, module_path, file)` and `line`. The idea is that a module could have more than one log calls, so most likely, these log calls would have the same `(target, module_path, file)` triple, group them together will allow multiple log calls to reuse a same `(target, module_path, file)` instance, see <https://godbolt.org/z/z7jW67Ece> for comparison.
For one of my internal projects, this PR will reduce the binary size by about 2%.
I also tested …

Group `target_module`, `path` and `file` arguments

---

CHANGELOG.md
Cargo.toml
src/lib.rs

* Remove rustversion dev-dependency by @Thomasdezeeuw in https://github.com/rust-lang/log/pull/568
* Remove `local_inner_macros` usage by @EFanZh in https://github.com/rust-lang/log/pull/570
* @EFanZh made their first contribution in https://github.com/rust-lang/log/pull/570

Prepare for 0.4.20 release

---

README.md
src/lib.rs

This adds a crate I've written and been using occasionally.
It's not something recommended for general use (its README explains the caveats; tl;dr: defmt benefits are gone once used with log), but when someone is on a defmt platform and briefly needs to capture a logging crate reports, this list is probably where they're looking.

doc: Add log-to-defmt to other-facilities section

---

benches/value.rs
src/kv/source.rs
src/lib.rs
src/serde.rs
tests/macros.rs

* Fix semicolons (pedantic)
* Don't duplicate var name for instantiation if not needed
* Use `mar_or` instead of `map.unwrap_or`

Minor clippy nits

---

src/kv/error.rs

For some reason, `fmt::Display for Error` uses an unusual form `match &self.inner { &Value(ref err) => err.fmt(f), ...}`.  It seems `Value(err)` will work just as well.
If this is actually needed, we should add some comment explaining why so

Simplify Display impl

---

.github/workflows/main.yml
Cargo.toml
benches/value.rs
rfcs/0296-structured-logging.md
src/kv/key.rs
src/kv/source.rs
src/kv/value.rs
src/lib.rs
src/serde.rs
test_max_level_features/Cargo.toml
test_max_level_features/main.rs
tests/Cargo.toml
tests/filters.rs
tests/macros.rs
tests/src/lib.rs

For some reason all crates still use 2015 edition. I think it is a good idea to specify edition explicitly, or at least document why it should be kept back (and still add it to the cargo.toml for documentation purposes)
* Remove all `extern crate`
* changed `use self::sval::...` to `use sval::...`, and the same for `sval_ref`
* Simplified `fn get<'v>(&'v self, key: Key) -> Option<Value<'v>>` to `fn get(&self, key: Key) -> Option<Value<'_>>`
* Simplified many unit tests with references

Set all crates to 2021 edition

---

src/kv/source.rs
src/kv/value.rs

It's easiest to review this by commit. Feel free to pick commits and drop others.

Various changes based on review

---

src/__private_api.rs
src/macros.rs

Currently, the `__private_api::log` function takes `None::<&[(&str, _)]>` as the `kvs` argument if no key-value pair is provided, but passing a `None` value may have some extra cost. We should be able to avoid this cost by encoding this information into a zero sized type (here I am using `()`, not sure if it is better to use a dedicated new type (such as `struct EmptyKVs;`)). Constructing a zero sized value is zero cost, which is less than constructing a `None::<&[(&str, _)]>`.

Specialize empty key value pairs

---

src/kv/value.rs

Without this change, the following code will not compile:
```Rust
let foo = record
.key_values()
.get(Key::from_str("foo"))
.and_then(|val| val.to_str());
```
with the following error:
```lang-none
|
32 |         .and_then(|val| val.to_str());
|                         ^^^^^^^^^^^^ returns a reference to data owned by the current function
```

Fix incorrect lifetime in Value::to_str()

---

README.md
src/lib.rs

logcontrol-log provides a log adaptor for the systemd logcontrol interface which enables on-the-fly reconfiguration of logging over DBus.
log-reload is a utility crate providing a log implementation that can dynamically modify and replace an underlying logger.  It backs the logcontrol-log implementation.
Disclaimer: These are my crates, but I find them very useful in system services, so I hope this doesn't qualify as self promotion.

Add logcontrol-log and log-reload

---

src/lib.rs

Rephrase the documentation to make it clear that the `max_level_*` features are also used by release builds.
With the MSRV bump, new language features allow initializing the constant in a way that's conciser and hopefully clearer.
Add some tests, used to validate the change.

Clarify documentation and simplify initialization of `STATIC_MAX_LEVEL`

---

CHANGELOG.md
README.md
rfcs/0296-structured-logging.md
src/kv/value.rs
src/lib.rs
src/macros.rs
tests/macros.rs

* Inline format arg in documentation and a few call places
* Add a unit test for inlined format args
I was surprised to discover that log crate has no edition value... Any reason to keep it at 2015?

Update docs to 2021 edition, test

---

README.md

Hi, 
I wrote a utility crate for log. To promote it, I though it is a good Idea to add a link to the log README file. Here is the corresponding PR.
Cheers Simon

Add "alterable_logger" link to README.md

---

src/lib.rs

Usages of `Option::ok_or` were removed because it was unstable at the time. It is now stable of MSRV.

Remove `ok_or` in favor of `Option::ok_or`

---

src/lib.rs

Reasoning is provided in a comment.

Use `Acquire` ordering for initialization check

---

.github/workflows/main.yml
Cargo.toml
README.md
benches/value.rs
src/__private_api.rs
src/kv/error.rs
src/kv/key.rs
src/kv/mod.rs
src/kv/source.rs
src/kv/value.rs
src/lib.rs
src/macros.rs
tests/Cargo.toml
tests/macros.rs

Closes #149 
Closes #328 
Closes #357 
Closes #436 
Closes #584 
Based on the review in #584
The plan is to:
I'll cc once this is ready for review, to save a bit of notification noise.
Once this PR is complete, we should be able to stabilize structured logging support in the `log` crate.

Get structured logging API ready for stabilization

---

CHANGELOG.md
Cargo.toml
src/lib.rs

cc @Thomasdezeeuw @JohnTitor This release stabilizes our structured logging API.
Closes #616 
* Minor clippy nits by @nyurik in https://github.com/rust-lang/log/pull/578
* Simplify Display impl by @nyurik in https://github.com/rust-lang/log/pull/579
* Set all crates to 2021 edition by @nyurik in https://github.com/rust-lang/log/pull/580
* Various changes based on review by @Thomasdezeeuw in https://github.com/rust-lang/log/pull/583
* Fix typo in file_static() method doc by @dimo414 in https://github.com/rust-lang/log/pull/590
* Specialize empty key value pairs by @EFanZh in https://github.com/rust-lang/log/pull/576
* Fix incorrect lifetime in Value::to_str() by @peterjoel in https://github.com/rust-lang/log/pull/587
* Remove some API of the key-value feature by @Thomasdezeeuw in …

Prepare for 0.4.21 release

---

src/lib.rs

Closes #522
Closes #556
This PR just adds some clarifications that have been suggested in issues.

Add some clarifications to the library docs

---

README.md
src/lib.rs

Hi 👋
I'm the maintained or the [colog](https://crates.io/crates/colog) crate.
My crate provides a quick way to set up colored logging with a (subjectively) good and clean look.
I've just released version 1.3, which in my opinion is hugely improved.
Everything is now extensively documented, and there are 7 included examples on using the crate. The crate has been around for 8 years, so it's not exactly abandonware ;-)
I would greatly appreciate it, if you would include it in the list of possible logging crates in your documentation (see this PR)

Add links to `colog` crate

---

src/lib.rs

Includes #622
I noticed our docs for these functions could use a bit more direct wording around exactly what they could race with.

Clarify the actual set of functions that can race in _racy variants

---

src/lib.rs

I noticed that `log`'s MSRV is now 1.60.0+, which seems to indicate that the TODO that was waiting for MSRV 1.49.0 can now be fulfilled.

Replace deprecated std::sync::atomic::spin_loop_hint()

---

.github/workflows/main.yml
src/lib.rs

With this change log will to fail to compile if two or more (release_)max_level_* features are used.
Closes #481

Check usage of max_level features

---

src/lib.rs
tests/Cargo.toml

This is a reworking of #520 using the same orderings. I think the main improvement was made in #610 so if we want to punt on this I think we reasonably can.

Loosen orderings for logger initialization

---

src/__private_api.rs
src/lib.rs
src/macros.rs
tests/Cargo.toml

Rework of #599. I've followed the suggestion in https://github.com/rust-lang/log/pull/599#issuecomment-2143472357 to pass a `panic::Location` to our non-inlined private log function in the hope it will avoid bloating callsites.

Use Location::caller() for file and line info

---

CHANGELOG.md
Cargo.toml
src/lib.rs

* Add some clarifications to the library docs by @KodrAus in https://github.com/rust-lang/log/pull/620
* Add links to `colog` crate by @chrivers in https://github.com/rust-lang/log/pull/621
* adding line_number test + updating some testing infrastructure by @DIvkov575 in https://github.com/rust-lang/log/pull/619
* Clarify the actual set of functions that can race in _racy variants by @KodrAus in https://github.com/rust-lang/log/pull/623
* Replace deprecated std::sync::atomic::spin_loop_hint() by @Catamantaloedis in https://github.com/rust-lang/log/pull/625
* Check usage of max_level features by @Thomasdezeeuw in https://github.com/rust-lang/log/pull/627
* Remove unneeded import by @Thomasdezeeuw in https://github.com/rust-lang/log/pull/628
* Loosen orderings for logger initialization in …

Prepare for 0.4.22 release

---

README.md

Hi, I would like to add a link to my personal project [`spdlog-rs`](https://github.com/SpriteOvO/spdlog-rs) to the README. It is inspired by the C++ logging library ``spdlog`` and is designed to provide performance benefits.
Based on [the benchmarks](https://github.com/SpriteOvO/spdlog-rs/blob/06aaa90ae9f646e2b7e8058700cd526583da05a7/spdlog/benches/README.md), it's probably the fastest logging crate yet. And it is also compatible with `log` crate.
I've been maintaining this project for 3 years and today I released its [v0.4.0](https://github.com/SpriteOvO/spdlog-rs/releases/tag/v0.4.0) version. I believe it is ready to be used by more users.

Add `spdlog-rs` link to README

---

src/lib.rs

This is added in https://github.com/rust-lang/log/pull/638.

docs: Add logforth as an impl

---

src/kv/key.rs

This allows things inside a Visitor to persist these strings for the lifetime of 'k without having to copy them.

Bind lifetimes of &str returned from Key by the lifetime of 'k rather than the lifetime of the Key struct

---

src/kv/key.rs

Follow-up to #648 
cc @gbbosak @Thomasdezeeuw 
This PR restores `Key`'s ability to store buffered values in the future for ease of integration, but introduces a method to try get a borrowed key from one.

Fix up key lifetimes and add method to try get a borrowed key

---

README.md
src/lib.rs

Adds [Ftail](https://crates.io/crates/ftail) to the list of 'simple minimal loggers'.
Ftail is a simple log implementation that allows logging to the console, a single file, a daily rotating file and to add your own custom option.
Thanks!

Add Ftail implementation

---

.github/workflows/main.yml
src/kv/value.rs
src/lib.rs

This closes https://github.com/rust-lang/log/issues/654#issuecomment-2581445570.
While I agree @KodrAus's comment at https://github.com/rust-lang/log/issues/654#issuecomment-2581494083, this is not a generally breaking down kv_x to kv + x.
But that value's `std_support` can work with kv + std. `kv_std` introduces an extra feature of `value-bag/error`, which is only used for:
```rust
pub fn to_borrowed_error(&self) -> Option<&(dyn std::error::Error + 'static)> {
self.inner.to_borrowed_error()
}
```
above.

Relax feature flag for value's std_support

---

Cargo.toml
src/kv/value.rs

Closes #661 
cc @Thomasdezeeuw @tisonkun
In #657 we moved some `kv_std` code into `kv` + `std`, but this unfortunately has hit a Cargo bug (see #661), which causes our `kv` dependencies to always end up in a dependents lockfile. Until the Cargo bug is fixed, or we find a different approach, I think we unfortunately need to revert this.

Revert loosening of kv cargo features

---

CHANGELOG.md
Cargo.toml
src/lib.rs

* Revert loosening of kv cargo features by @KodrAus in https://github.com/rust-lang/log/pull/662

Prepare for 0.4.25 release

---

src/kv/value.rs

Derive `Clone` for `kv::Value`

---

src/lib.rs

PR #639 only added the link to README, but forgot to add it in the crate doc.
I apologize for opening another new PR for this.

Add `spdlog-rs` link to crate doc

---

CHANGELOG.md
Cargo.toml
src/lib.rs

* Derive `Clone` for `kv::Value` by @SpriteOvO in https://github.com/rust-lang/log/pull/668
* Add `spdlog-rs` link to crate doc by @SpriteOvO in https://github.com/rust-lang/log/pull/669

Prepare for 0.4.26 release

---

src/macros.rs

Add `#[clippy::format_args]` as described in [Clippy book](https://doc.rust-lang.org/nightly/clippy/attribs.html#clippyformat_args)
This is a new feature in v1.85

Enable clippy support for format-like macros

---

src/__private_api.rs
src/lib.rs
src/macros.rs
tests/integration.rs
tests/macros.rs

This closes #645 
@KodrAus I noticed that we previously introduced `target` for similar usage, but switching to a different logger is different.
This patch is for preview. I'm not quite sure how we pass the customized logger. The current implementation seems good. I think the `log` crate itself isn't suitable to hold a global `name -> logger` registry: that would be too heavy and too specific.

Add an optional logger param

---

src/__private_api.rs
src/macros.rs
tests/integration.rs
tests/macros.rs

Follow-up to #664 
cc @EFanZh @tisonkun @Thomasdezeeuw 
This PR ensures we pass loggers by-ref when they're user-supplied, and by-value when it's the built-in global logger. I'll add a few tests to ensure we don't take ownership of the logger in `log!` or `log_enabled!`.

Pass global logger by value, supplied logger by ref

---

src/kv/mod.rs

Makes no sense to hide this, as `impl Debug for Value` forwards to the `inner`'s `Debug` impl

Unhide `#[derive(Debug)]` in example

---

src/lib.rs

I noticed two of the implementations called out in the README are missing from the almost identical list in the root docs.  This adds them there as well.

docs: Add missing impls from README.md

---

src/lib.rs

Logos and favicon links for the docs are broken, this changes the URLs to point to the new location

Point to new URLs for favicon and logo
